### ISSUE TITLE
Version 24.0 Progress

### ISSUE THREAD

**Issue by actionschnitzel** [actionschnitzel/PiGro-Aid-#74]
# Testing
- [x] Coding Phase
- [x] Start Test Phase
- [x] Review Feedback
- [x] RC1 State
- [x] Fine Tuning
- [ ] Release Jan' 24
## 1st Test Feedback
- [x] Remove PiGro.desktop file
- [x] Check Update && Upgrade does not all upgrades [Not reproduceble yet]
- [x] Check Raspi-Config CLI in SYSTEM 
- [x] Check Papirus not working [ Tool will be improved]
- [x] Check set Theme, Icons, Cursor [ PiOS is not able to be riced]
- [x] Check folder not opening
- [x] Chack Tuning States not displayed
Fixed in: c183ea3555aaaa56a5520f7e60c2d36687f9f838 , 1a11ff09e4b42a3f61c20b661dbdf0ee160fc5e1 , 75f060d35d4f629336ff7fba02db7c97b7eef163 , e9739c7878e7abec46542a2cec824b8372a21719

## 2st Test Feedback
- [x] Add solution to recover lxterminal as default(while installing DEB)
- [x]  The theming for PiOS X11 & Wayland
- [x] Improve Screenshot scaling in Software
- [x] Improve Software Tab LODING TIME
- [x] One Click instead of Double Click in Software
- [x] passwordless SUDO?
- [x] Raspi Appearance Settings Doubled
- [x] More ToolTips
- [x] Check for misspelled words
- [x] Button state at interupt
- [x] Bring back  one-click installers
- [x] Implement More Ram installer
# Verified
- [x] Raspberry Pi 5 compatibility
- [x] Raspberry Pi 4 compatibility
- [x] Raspberry Pi OS compatibility
- [x] Ubuntu 23.10 compatibility
- [x] Raspberry Pi OS Legacy compatibility
- [x] Raspberry Pi OS Buster DROPED!
- [x] Implement amd64 DEV-MODE
- [x] Implementation of gsettings for better system access
- [x] Split PiGro into separate files
- [x] Global Theme Method
- [x] Dependency `gdebi`
- [x] Dependency `mousepad`
- [x] Dependency `wmctrl`

# To-Do

## Dashboard
- [x] All Live Stats 
- [x] Snap Package Counter
- [x] Check Internet Connection
- [x] Arm Model
- [x] Distro Logos

## Update
- [x] All Actions with pkexec
- [x] Replace dpkg -i with gdebi >>>> add gdebi to Dependiencies
- [x] Add Update Snap Button
- [x] Add Nala
- [x] Add Flatpak

## Sources
- [x] Add Button to open Folder

## System
- [x] Disable Button if tool not installed
- [x] Remove "Update Linux Kernel" > Not working anymore
- [x] Fix FM GODE MODE
- [x] Add `sudo dpkg-reconfigure keyboard-configuration` f6e8b5948502cdaf3e39b399f88bc00db46276b7
- [x] Add ` sudo dpkg-reconfigure locales` f6e8b5948502cdaf3e39b399f88bc00db46276b7
- [x] Add `dmesg --follow` f6e8b5948502cdaf3e39b399f88bc00db46276b7

## Look
- [x] Remove Tasksel, Change DE, Change WM
- [x] Disable Buttons that not work in Bullseye

## Autostart
- [x] Theme Widgets

## Tasks
- [x] Theme Button

## Software
- [x] Make all Tabs alike APT
- [x] Move Nice 2 Have to Software Tab

## Tuning
- [x] Disable Pi4 Presets on Pi5
- [x] Add new Overvoltage SpinBox
- [x] Merge Custom Setting with Current Settings
- [x] Remove Chromium32 installer
- [x] Improve SWAP/Z-RAM Management

## All
- [x] Dash
- [x] Update
- [x] Source
- [x] System
- [x] Look
- [x] Auto
- [x] Task
- [x] Software
- [x] Nice
- [x] Tuning
- [x] Backup
- [x] Links
- [x] About
- [x] PopUps
- [x] Resorcess

##  **Impressions**

![Bildschirmfoto vom 2023-11-10 12-27-53](https://github.com/actionschnitzel/PiGro-Aid-/assets/67635013/b56d0907-840d-43e1-8c95-59769da339e2)
